Repository boostcampwm2023/and03_movemove, pull requests merged in 2023-11, with the labels that each got.

#5 프로젝트 셋업
  client/app/src/main/java/com/everyone/movemove_android/MainActivity.kt
  client/build.gradle.kts
  client/data/.gitignore
  client/data/build.gradle.kts
  client/data/consumer-rules.pro
  client/data/proguard-rules.pro
  client/data/src/androidTest/java/com/everyone/data/ExampleInstrumentedTest.kt
  client/data/src/main/AndroidManifest.xml
  client/data/src/test/java/com/everyone/data/ExampleUnitTest.kt
  client/domain/.gitignore
  client/domain/build.gradle.kts
  client/domain/consumer-rules.pro
  client/domain/proguard-rules.pro
  client/domain/src/androidTest/java/com/everyone/domain/ExampleInstrumentedTest.kt
  client/domain/src/main/AndroidManifest.xml
  client/domain/src/test/java/com/everyone/domain/ExampleUnitTest.kt
  client/gradle/libs.versions.toml
  client/gradle/wrapper/gradle-wrapper.properties
  client/gradlew
  client/gradlew.bat
  client/presentation/.gitignore
  client/presentation/build.gradle.kts
  client/presentation/proguard-rules.pro
  client/presentation/src/androidTest/java/com/everyone/movemove_android/ExampleInstrumentedTest.kt
  client/presentation/src/main/AndroidManifest.xml
  client/presentation/src/main/java/com/everyone/movemove_android/App.kt
  client/presentation/src/main/java/com/everyone/movemove_android/base/BaseActivity.kt
  client/presentation/src/main/java/com/everyone/movemove_android/base/BaseContract.kt
  client/presentation/src/main/java/com/everyone/movemove_android/base/BaseViewModel.kt
  client/presentation/src/main/java/com/everyone/movemove_android/di/CoroutineDispatcherModule.kt
  client/presentation/src/main/java/com/everyone/movemove_android/di/CoroutineDispatcherQualifiers.kt
  client/presentation/src/main/java/com/everyone/movemove_android/ui/main/MainActivity.kt
  client/presentation/src/main/java/com/everyone/movemove_android/ui/theme/Color.kt
  client/presentation/src/main/java/com/everyone/movemove_android/ui/theme/Theme.kt
  client/presentation/src/main/java/com/everyone/movemove_android/ui/theme/Type.kt
  client/presentation/src/main/java/com/everyone/movemove_android/ui/util/ComposableUtil.kt
  client/presentation/src/main/res/drawable/ic_launcher_background.xml
  client/presentation/src/main/res/drawable/ic_launcher_foreground.xml
  client/presentation/src/main/res/mipmap-anydpi/ic_launcher.xml
  client/presentation/src/main/res/mipmap-anydpi/ic_launcher_round.xml
  client/presentation/src/main/res/mipmap-hdpi/ic_launcher.webp
  client/presentation/src/main/res/mipmap-hdpi/ic_launcher_round.webp
  client/presentation/src/main/res/mipmap-mdpi/ic_launcher.webp
  client/presentation/src/main/res/mipmap-mdpi/ic_launcher_round.webp
  client/presentation/src/main/res/mipmap-xhdpi/ic_launcher.webp
  client/presentation/src/main/res/mipmap-xhdpi/ic_launcher_round.webp
  client/presentation/src/main/res/mipmap-xxhdpi/ic_launcher.webp
  client/presentation/src/main/res/mipmap-xxhdpi/ic_launcher_round.webp
  client/presentation/src/main/res/mipmap-xxxhdpi/ic_launcher.webp
  client/presentation/src/main/res/mipmap-xxxhdpi/ic_launcher_round.webp
  client/presentation/src/main/res/values/colors.xml
  client/presentation/src/main/res/values/strings.xml
  client/presentation/src/main/res/values/themes.xml
  client/presentation/src/main/res/xml/backup_rules.xml
  client/presentation/src/main/res/xml/data_extraction_rules.xml
  client/presentation/src/test/java/com/everyone/movemove_android/ExampleUnitTest.kt
  client/settings.gradle.kts
Labels: android, feat, chore

#7 UI 시스템 Compose 셋업
  client/presentation/src/main/java/com/everyone/movemove_android/base/StateDispatcher.kt
  client/presentation/src/main/java/com/everyone/movemove_android/ui/theme/Color.kt
  client/presentation/src/main/java/com/everyone/movemove_android/ui/theme/Font.kt
  client/presentation/src/main/java/com/everyone/movemove_android/ui/theme/Theme.kt
  client/presentation/src/main/java/com/everyone/movemove_android/ui/theme/Type.kt
  client/presentation/src/main/java/com/everyone/movemove_android/ui/util/ComposableUtil.kt
  client/presentation/src/main/res/font/pretendard_bold.otf
  client/presentation/src/main/res/font/pretendard_medium.otf
  client/presentation/src/main/res/font/pretendard_regular.otf
  client/presentation/src/main/res/font/pretendard_semi_bold.otf
  client/presentation/src/main/res/font/pretendard_thin.otf
Labels: android, feat, chore

#11 기본 Composable 구현
  client/presentation/src/main/java/com/everyone/movemove_android/base/BaseActivity.kt
  client/presentation/src/main/java/com/everyone/movemove_android/ui/CommonComposables.kt
  client/presentation/src/main/java/com/everyone/movemove_android/ui/main/MainActivity.kt
  client/presentation/src/main/java/com/everyone/movemove_android/ui/theme/Color.kt
  client/presentation/src/main/java/com/everyone/movemove_android/ui/theme/Theme.kt
Labels: android, feat, chore

#13 바텀 네비게이션 구현
  client/presentation/src/main/java/com/everyone/movemove_android/ui/main/MainActivity.kt
  client/presentation/src/main/java/com/everyone/movemove_android/ui/main/MainScreen.kt
  client/presentation/src/main/java/com/everyone/movemove_android/ui/main/home/HomeScreen.kt
  client/presentation/src/main/java/com/everyone/movemove_android/ui/main/my/MyScreen.kt
  client/presentation/src/main/java/com/everyone/movemove_android/ui/main/navigation/Destination.kt
  client/presentation/src/main/java/com/everyone/movemove_android/ui/main/navigation/Navigator.kt
  client/presentation/src/main/java/com/everyone/movemove_android/ui/main/uploading_video/UploadingVideoScreen.kt
  client/presentation/src/main/java/com/everyone/movemove_android/ui/main/watching_video/WatchingVideoScreen.kt
  client/presentation/src/main/java/com/everyone/movemove_android/ui/theme/Color.kt
  client/presentation/src/main/res/drawable/ic_home.xml
  client/presentation/src/main/res/drawable/ic_my.xml
  client/presentation/src/main/res/drawable/ic_uploading_video.xml
  client/presentation/src/main/res/drawable/ic_watching_video.xml
  client/presentation/src/main/res/values/strings.xml
Labels: android, feat, chore

#19 바텀 네비게이션 스타일 수정
  client/presentation/src/main/java/com/everyone/movemove_android/ui/main/MainScreen.kt
Labels: android, fix

#21 프로젝트 셋업
  .DS_Store
  .gitignore
  server/.eslintrc.js
  server/.gitignore
  server/.prettierrc
  server/README.md
  server/nest-cli.json
  server/package-lock.json
  server/package.json
  server/src/action/action.controller.ts
  server/src/action/action.module.ts
  server/src/action/action.service.ts
  server/src/action/schemas/action.schema.ts
  server/src/app.controller.ts
  server/src/app.module.ts
  server/src/app.service.ts
  server/src/auth/auth.controller.ts
  server/src/auth/auth.module.ts
  server/src/auth/auth.service.ts
  server/src/main.ts
  server/src/user/dto/user.dto.ts
  server/src/user/schemas/user.schema.ts
  server/src/user/user.controller.ts
  server/src/user/user.module.ts
  server/src/user/user.service.ts
  server/src/video/dto/video.dto.ts
  server/src/video/schemas/video.schema.ts
  server/src/video/video.controller.ts
  server/src/video/video.module.ts
  server/src/video/video.service.ts
  server/test/app.e2e-spec.ts
  server/test/jest-e2e.json
  server/tsconfig.build.json
  server/tsconfig.json
  server/yarn.lock
Labels: backend, feat, chore

#20 숏 폼 비디오 스트리밍
  client/gradle/libs.versions.toml
  client/presentation/build.gradle.kts
  client/presentation/src/main/AndroidManifest.xml
  client/presentation/src/main/java/com/everyone/movemove_android/ui/main/watching_video/WatchingVideoScreen.kt
  client/presentation/src/main/java/com/everyone/movemove_android/ui/theme/Color.kt
  client/presentation/src/main/java/com/everyone/movemove_android/ui/theme/Type.kt
Labels: android, feat

#25 DB 설계
  .gitignore
  server/src/action/schemas/action.schema.ts
  server/src/user/schemas/user.schema.ts
  server/src/video/schemas/video.schema.ts
  server/src/video/video.controller.ts
Labels: backend, feat, chore

#31 NCP 업로드 API 작성
  server/.eslintrc.js
  server/package.json
  server/src/app.controller.ts
  server/src/ncpAPI/common.ts
  server/src/ncpAPI/putObject.ts
  server/yarn.lock
Labels: backend, feat

#30 인코딩 요청 API 작성
  server/README.md
  server/package.json
  server/src/app.controller.ts
  server/src/ncpAPI/common.ts
  server/src/ncpAPI/requestEncoding.ts
  server/yarn.lock
Labels: backend, feat

#33 HLS 비디오 스트리밍
  client/gradle/libs.versions.toml
  client/presentation/src/main/java/com/everyone/movemove_android/ui/main/watching_video/WatchingVideoScreen.kt
Labels: android, feat

#36 NCP 삭제 API 작성
  server/src/app.controller.ts
  server/src/ncpAPI/deleteObject.ts
  server/src/ncpAPI/requestEncoding.ts
Labels: backend, feat

#34 비디오 스트리밍 최적화
  client/presentation/src/main/java/com/everyone/movemove_android/ui/main/watching_video/WatchingVideoScreen.kt
Labels: android, fix

#38 백엔드 코딩컨벤션 설정
  server/.eslintrc.js
  server/package-lock.json
  server/package.json
  server/src/app.controller.ts
  server/src/app.module.ts
  server/src/auth/auth.controller.ts
  server/src/main.ts
  server/src/ncpAPI/common.ts
  server/src/ncpAPI/requestEncoding.ts
  server/src/user/dto/user.dto.ts
  server/src/user/user.controller.ts
  server/src/video/dto/video.dto.ts
  server/src/video/dto/videoRating.dto.ts
  server/src/video/schemas/video.schema.ts
  server/src/video/video.controller.ts
  server/src/video/video.service.ts
  server/yarn.lock
Labels: backend, chore

#39 비디오 스트리밍 점수 등록
  client/presentation/src/main/java/com/everyone/movemove_android/ui/main/watching_video/WatchingVideoScreen.kt
  client/presentation/src/main/res/values/strings.xml
Labels: android, feat

#43 영상 편집 기능 구현
  client/presentation/src/main/java/com/everyone/movemove_android/base/BaseViewModel.kt
  client/presentation/src/main/java/com/everyone/movemove_android/di/CoroutineDispatcherModule.kt
  client/presentation/src/main/java/com/everyone/movemove_android/di/CoroutineDispatcherQualifiers.kt
  client/presentation/src/main/java/com/everyone/movemove_android/ui/CommonComposables.kt
  client/presentation/src/main/java/com/everyone/movemove_android/ui/Dialogs.kt
  client/presentation/src/main/java/com/everyone/movemove_android/ui/main/MainActivity.kt
  client/presentation/src/main/java/com/everyone/movemove_android/ui/main/uploading_video/UploadingVideoContract.kt
  client/presentation/src/main/java/com/everyone/movemove_android/ui/main/uploading_video/UploadingVideoScreen.kt
  client/presentation/src/main/java/com/everyone/movemove_android/ui/main/uploading_video/UploadingVideoViewModel.kt
  client/presentation/src/main/java/com/everyone/movemove_android/ui/main/uploading_video/VideoTrimmer.kt
  client/presentation/src/main/java/com/everyone/movemove_android/ui/theme/Color.kt
  client/presentation/src/main/java/com/everyone/movemove_android/ui/util/ComposableUtil.kt
  client/presentation/src/main/java/com/everyone/movemove_android/ui/util/Util.kt
  client/presentation/src/main/res/drawable/ic_pause.xml
  client/presentation/src/main/res/drawable/ic_play.xml
  client/presentation/src/main/res/values/strings.xml
Labels: android, feat, refactor

#45 비디오 스트리밍 카테고리 변경
  client/presentation/src/main/java/com/everyone/movemove_android/ui/main/watching_video/WatchingVideoContract.kt
  client/presentation/src/main/java/com/everyone/movemove_android/ui/main/watching_video/WatchingVideoScreen.kt
  client/presentation/src/main/java/com/everyone/movemove_android/ui/main/watching_video/WatchingVideoViewModel.kt
  client/presentation/src/main/java/com/everyone/movemove_android/ui/main/watching_video/category/CategoryScreen.kt
  client/presentation/src/main/java/com/everyone/movemove_android/ui/theme/Color.kt
  client/presentation/src/main/res/drawable/ic_close.xml
  client/presentation/src/main/res/drawable/ic_expand_more.xml
  client/presentation/src/main/res/values/strings.xml
Labels: android, feat

#52 카테고리 목록 안나오는 이슈
  client/presentation/src/main/java/com/everyone/movemove_android/ui/main/watching_video/WatchingVideoContract.kt
  client/presentation/src/main/java/com/everyone/movemove_android/ui/main/watching_video/WatchingVideoScreen.kt
  client/presentation/src/main/java/com/everyone/movemove_android/ui/main/watching_video/category/CategoryScreen.kt
Labels: android, fix

#53 다른 팀 서비스 광고
  client/gradle/libs.versions.toml
  client/presentation/src/main/java/com/everyone/movemove_android/ui/main/home/HomeScreen.kt
Labels: android, feat

#54 메인 페이지 비디오 모아보기
  client/presentation/src/main/java/com/everyone/movemove_android/ui/main/MainScreen.kt
  client/presentation/src/main/java/com/everyone/movemove_android/ui/main/home/HomeContract.kt
  client/presentation/src/main/java/com/everyone/movemove_android/ui/main/home/HomeScreen.kt
  client/presentation/src/main/java/com/everyone/movemove_android/ui/main/home/HomeViewModel.kt
  client/presentation/src/main/res/values/strings.xml
Labels: android, feat

#41 회원가입시 프로필 및 유저정보 저장
  server/nest-cli.json
  server/package.json
  server/src/action/schemas/action.schema.ts
  server/src/app.module.ts
  server/src/auth/auth.controller.ts
  server/src/auth/auth.module.ts
  server/src/auth/auth.service.ts
  server/src/enum/exception.enum.ts
  server/src/exceptions/base.exception.ts
  server/src/exceptions/conflict.exception.ts
  server/src/main.ts
  server/src/user/dto/user.dto.ts
  server/yarn.lock
Labels: backend, feat

#56 스크린 변경 애니메이션 삭제
  client/gradle/libs.versions.toml
  client/presentation/src/main/java/com/everyone/movemove_android/ui/main/MainScreen.kt
Labels: android, chore

#47 카카오, 구글 로그인 구현
  client/gradle/libs.versions.toml
  client/presentation/build.gradle.kts
  client/presentation/src/main/AndroidManifest.xml
  client/presentation/src/main/java/com/everyone/movemove_android/App.kt
  client/presentation/src/main/java/com/everyone/movemove_android/ui/login/LoginActivity.kt
  client/presentation/src/main/java/com/everyone/movemove_android/ui/login/LoginContract.kt
  client/presentation/src/main/java/com/everyone/movemove_android/ui/login/LoginScreen.kt
  client/presentation/src/main/java/com/everyone/movemove_android/ui/login/LoginViewModel.kt
  client/presentation/src/main/java/com/everyone/movemove_android/ui/theme/Color.kt
  client/presentation/src/main/res/drawable/ic_kakao_login.xml
  client/presentation/src/main/res/drawable/img_google_login.png
  client/presentation/src/main/res/values/strings.xml
  client/settings.gradle.kts
Labels: android, feat

#62 패키지 구조 및 이름 수정
  client/presentation/src/main/AndroidManifest.xml
  client/presentation/src/main/java/com/everyone/movemove_android/ui/container/ContainerActivity.kt
  client/presentation/src/main/java/com/everyone/movemove_android/ui/container/ContainerScreen.kt
  client/presentation/src/main/java/com/everyone/movemove_android/ui/container/navigation/Destination.kt
  client/presentation/src/main/java/com/everyone/movemove_android/ui/container/navigation/Navigator.kt
  client/presentation/src/main/java/com/everyone/movemove_android/ui/screens/home/HomeContract.kt
  client/presentation/src/main/java/com/everyone/movemove_android/ui/screens/home/HomeScreen.kt
  client/presentation/src/main/java/com/everyone/movemove_android/ui/screens/home/HomeViewModel.kt
  client/presentation/src/main/java/com/everyone/movemove_android/ui/screens/profile/ProfileScreen.kt
  client/presentation/src/main/java/com/everyone/movemove_android/ui/screens/uploading_video/UploadingVideoContract.kt
  client/presentation/src/main/java/com/everyone/movemove_android/ui/screens/uploading_video/UploadingVideoScreen.kt
  client/presentation/src/main/java/com/everyone/movemove_android/ui/screens/uploading_video/UploadingVideoViewModel.kt
  client/presentation/src/main/java/com/everyone/movemove_android/ui/screens/uploading_video/VideoTrimmer.kt
  client/presentation/src/main/java/com/everyone/movemove_android/ui/screens/watching_video/WatchingVideoContract.kt
  client/presentation/src/main/java/com/everyone/movemove_android/ui/screens/watching_video/WatchingVideoScreen.kt
  client/presentation/src/main/java/com/everyone/movemove_android/ui/screens/watching_video/WatchingVideoViewModel.kt
  client/presentation/src/main/java/com/everyone/movemove_android/ui/screens/watching_video/category/CategoryScreen.kt
  client/presentation/src/main/res/values/strings.xml
Labels: android, refactor

#63 영상 업로드 화면 바텀 시트 추가
  client/domain/src/main/java/com/everyone/domain/model/Category.kt
  client/gradle/libs.versions.toml
  client/presentation/src/main/java/com/everyone/movemove_android/ui/screens/uploading_video/UploadingVideoContract.kt
  client/presentation/src/main/java/com/everyone/movemove_android/ui/screens/uploading_video/UploadingVideoScreen.kt
  client/presentation/src/main/java/com/everyone/movemove_android/ui/screens/uploading_video/UploadingVideoViewModel.kt
  client/presentation/src/main/res/values/strings.xml
Labels: android, feat

#70 인증 및 비디오 업로드 통합
  server/src/auth/auth.service.ts
  server/src/enum/exception.enum.ts
  server/src/exceptions/base.exception.ts
  server/src/exceptions/conflict.exception.ts
  server/src/exceptions/invalid-refresh-token.exception.ts
  server/src/exceptions/invalid-token.exception.ts
  server/src/exceptions/login-fail.exception.ts
  server/src/exceptions/oauth-failed.exception.ts
  server/src/exceptions/token-expired.exception.ts
  server/src/main.ts
  server/src/video/video.controller.ts
  server/src/video/video.module.ts
Labels: backend, feat

#73 랜덤 비디오 응답
  server/src/auth/auth.service.ts
  server/src/main.ts
  server/src/ncpAPI/getObject.ts
  server/src/user/schemas/user.schema.ts
  server/src/video/dto/random-video-query.dto.ts
  server/src/video/video.controller.ts
  server/src/video/video.service.ts
Labels: backend, feat

#74 업로드한 비디오 삭제
  server/src/app.controller.ts
  server/src/auth/auth.controller.ts
  server/src/decorators/api-succes-response.ts
  server/src/decorators/request-user.ts
  server/src/enum/exception.enum.ts
  server/src/exceptions/base.exception.ts
  server/src/exceptions/not-your-video.exception.ts
  server/src/exceptions/video-not-found.exception.ts
  server/src/http-Exception.filter.ts
  server/src/user/dto/profile-response.dto.ts
  server/src/user/dto/user.dto.ts
  server/src/video/schemas/video.schema.ts
  server/src/video/video.controller.ts
  server/src/video/video.service.ts
Labels: backend, feat

#77 회원가입 시 기본 프로필 이미지 지원
  .vscode/settings.json
  server/src/app.controller.ts
  server/src/auth/auth.controller.ts
  server/src/auth/auth.service.ts
  server/src/exceptions/base.exception.ts
  server/src/exceptions/conflict.exception.ts
  server/src/exceptions/enum/exception.enum.ts
  server/src/exceptions/invalid-refresh-token.exception.ts
  server/src/exceptions/invalid-token.exception.ts
  server/src/exceptions/login-fail.exception.ts
  server/src/exceptions/not-your-video.exception.ts
  server/src/exceptions/oauth-failed.exception.ts
  server/src/exceptions/token-expired.exception.ts
  server/src/exceptions/video-not-found.exception.ts
  server/src/user/dto/user.dto.ts
  server/src/video/video.controller.ts
  server/src/video/video.service.ts
Labels: backend, feat, fix

#79 버그 수정 및 Manifest 응답
  server/.gitignore
  server/src/auth/auth.module.ts
  server/src/auth/auth.service.ts
  server/src/video/video.service.ts
Labels: backend, feat, fix

#76 회원가입 ui 구현
  client/presentation/src/main/java/com/everyone/movemove_android/ui/screens/signup/SignUpContract.kt
  client/presentation/src/main/java/com/everyone/movemove_android/ui/screens/signup/SignUpScreen.kt
  client/presentation/src/main/java/com/everyone/movemove_android/ui/screens/signup/SignUpViewModel.kt
  client/presentation/src/main/java/com/everyone/movemove_android/ui/theme/Color.kt
  client/presentation/src/main/res/drawable/basic_profile.png
  client/presentation/src/main/res/drawable/ic_left_arrow.xml
  client/presentation/src/main/res/drawable/ic_profile_add.xml
  client/presentation/src/main/res/values/strings.xml
Labels: android, feat

#83 프로필 조회 및 변경
  server/package.json
  server/src/auth/auth.service.ts
  server/src/auth/dto/jwt.dto.ts
  server/src/auth/dto/signin-response.dto.ts
  server/src/auth/dto/signup-response.dto.ts
  server/src/decorators/api-fail-response.ts
  server/src/exceptions/enum/exception.enum.ts
  server/src/exceptions/user-not-found.exception.ts
  server/src/main.ts
  server/src/user/dto/profile-response.dto.ts
  server/src/user/dto/profile.dto.ts
  server/src/user/dto/user-info.dto.ts
  server/src/user/dto/user.dto.ts
  server/src/user/user.controller.ts
  server/src/user/user.module.ts
  server/src/user/user.service.ts
  server/yarn.lock
Labels: backend, feat

#89 네트워크 통신 셋업
  client/build.gradle.kts
  client/data/build.gradle.kts
  client/data/src/main/java/com/everyone/data/base/BaseResponse.kt
  client/data/src/main/java/com/everyone/data/remote/NetworkHandler.kt
  client/data/src/main/java/com/everyone/data/remote/UrlParams.kt
  client/data/src/main/java/com/everyone/data/remote/UrlParamsBuilder.kt
  client/domain/build.gradle.kts
  client/gradle/libs.versions.toml
  client/presentation/build.gradle.kts
Labels: android, feat, chore

#87 내가 업로드 한 영상 피드로 모아보기
  client/presentation/src/main/java/com/everyone/movemove_android/ui/screens/profile/ProfileContract.kt
  client/presentation/src/main/java/com/everyone/movemove_android/ui/screens/profile/ProfileScreen.kt
  client/presentation/src/main/java/com/everyone/movemove_android/ui/screens/profile/ProfileViewModel.kt
  client/presentation/src/main/res/drawable/ic_menu.xml
  client/presentation/src/main/res/values/strings.xml
Labels: android, feat

#91 UrlParamsBuilder 수정
  client/data/src/main/java/com/everyone/data/remote/UrlParams.kt
  client/data/src/main/java/com/everyone/data/remote/UrlParamsBuilder.kt
Labels: android, fix

#81 광고 이미지 반환
  server/package.json
  server/src/app.service.ts
  server/src/ncpAPI/listObjects.ts
  server/yarn.lock
Labels: backend, feat

#88 비디오 정보 조회
  server/src/decorators/api-succes-response.ts
  server/src/transform.interceptor.ts
  server/src/user/dto/profile.dto.ts
  server/src/user/dto/user.dto.ts
  server/src/user/user.controller.ts
  server/src/video/schemas/video.schema.ts
  server/src/video/video.service.ts
Labels: backend, feat

#85 특정 유저가 업로드 한 비디오 조회
  server/src/user/dto/uploaded-video-request.dto.ts
  server/src/user/dto/uploaded-video-response.dto.ts
  server/src/user/dto/uploader-response.dto.ts
  server/src/user/user.controller.ts
  server/src/user/user.module.ts
  server/src/user/user.service.ts
  server/src/video/dto/video-response.dto.ts
  server/src/video/schemas/video.schema.ts
Labels: backend, feat

#95 스플래시 화면 추가
  client/gradle/libs.versions.toml
  client/presentation/build.gradle.kts
  client/presentation/src/main/AndroidManifest.xml
  client/presentation/src/main/res/drawable/ic_title_point.xml
  client/presentation/src/main/res/drawable/ic_title_white.xml
  client/presentation/src/main/res/values/themes.xml
Labels: android, feat, chore

#105 Swagger 명세 구체화
  server/src/action/schemas/action.schema.ts
  server/src/app.service.ts
  server/src/ncpAPI/getBucketImage.ts
  server/src/transform.interceptor.ts
  server/src/user/dto/uploaded-video-response.dto.ts
  server/src/user/dto/uploader-response.dto.ts
  server/src/user/schemas/user.schema.ts
  server/src/user/user.controller.ts
  server/src/user/user.service.ts
  server/src/video/dto/random-video-response.dto.ts
  server/src/video/dto/video-info.dto.ts
  server/src/video/dto/video-response.dto.ts
  server/src/video/dto/video-summary-response.dto.ts
  server/src/video/schemas/video.schema.ts
  server/src/video/video.controller.ts
  server/src/video/video.service.ts
Labels: backend, feat, chore, refactor

#106 비디오 별점 등록/수정
  server/nest-cli.json
  server/src/action/action.module.ts
  server/src/action/action.service.ts
  server/src/action/schemas/action.schema.ts
  server/src/app.controller.ts
  server/src/auth/auth.controller.ts
  server/src/exceptions/enum/exception.enum.ts
  server/src/exceptions/never-view-video.exception.ts
  server/src/exceptions/reason-required.exception.ts
  server/src/user/user.controller.ts
  server/src/video/dto/video-rating-response.dto.ts
  server/src/video/dto/video-rating.dto.ts
  server/src/video/schemas/video.schema.ts
  server/src/video/video.controller.ts
  server/src/video/video.module.ts
  server/src/video/video.service.ts
Labels: backend, feat

#111 네트워크 통신 구조 적용
  client/data/build.gradle.kts
  client/data/src/main/java/com/everyone/data/base/BaseResponse.kt
  client/data/src/main/java/com/everyone/data/mapper/Mapper.kt
  client/data/src/main/java/com/everyone/data/remote/NetworkHandler.kt
  client/data/src/main/java/com/everyone/data/remote/model/ApiResponse.kt
  client/data/src/main/java/com/everyone/data/remote/model/UrlParams.kt
  client/data/src/main/java/com/everyone/data/remote/model/UrlParamsBuilder.kt
  client/domain/src/main/java/com/everyone/domain/model/base/BaseModel.kt
  client/presentation/src/main/java/com/everyone/movemove_android/di/NetworkHandlerModule.kt
Labels: android, feat, chore

#112 비디오 스트리밍 후 백그라운드로 이동 시 ExoPlayer 정지
  client/presentation/src/main/java/com/everyone/movemove_android/ui/screens/watching_video/WatchingVideoScreen.kt
Labels: android, fix

#121 비디오 스트리밍 페이지 API 연결
  client/data/src/main/java/com/everyone/data/remote/NetworkHandler.kt
  client/data/src/main/java/com/everyone/data/remote/model/UploaderResponse.kt
  client/data/src/main/java/com/everyone/data/remote/model/VideoRandomResponse.kt
  client/data/src/main/java/com/everyone/data/remote/model/VideoResponse.kt
  client/data/src/main/java/com/everyone/data/remote/model/VideosRandomResponse.kt
  client/data/src/main/java/com/everyone/data/repository/MainRepositoryImpl.kt
  client/domain/src/main/java/com/everyone/domain/model/Uploader.kt
  client/domain/src/main/java/com/everyone/domain/model/Video.kt
  client/domain/src/main/java/com/everyone/domain/model/VideoRandom.kt
  client/domain/src/main/java/com/everyone/domain/model/VideosRandom.kt
  client/domain/src/main/java/com/everyone/domain/repository/MainRepository.kt
  client/domain/src/main/java/com/everyone/domain/usecase/GetVideoRandomUseCase.kt
  client/domain/src/main/java/com/everyone/domain/usecase/PutVideosRatingUseCase.kt
  client/presentation/src/main/java/com/everyone/movemove_android/di/RepositoryModule.kt
  client/presentation/src/main/java/com/everyone/movemove_android/ui/screens/watching_video/WatchingVideoViewModel.kt
Labels: android, feat

#122 마이 화면 UI 구현
  client/presentation/src/main/AndroidManifest.xml
  client/presentation/src/main/java/com/everyone/movemove_android/ui/my/MyActivity.kt
  client/presentation/src/main/java/com/everyone/movemove_android/ui/my/MyScreen.kt
  client/presentation/src/main/java/com/everyone/movemove_android/ui/screens/signup/SignUpScreen.kt
  client/presentation/src/main/res/drawable/basic_profile.png
  client/presentation/src/main/res/drawable/ic_heart.xml
  client/presentation/src/main/res/drawable/ic_my_video.xml
  client/presentation/src/main/res/drawable/ic_profile_edit.xml
  client/presentation/src/main/res/drawable/img_basic_profile.png
  client/presentation/src/main/res/values/strings.xml
Labels: android, feat

#113 특정 유저가 별점을 준 비디오 조회
  server/src/ncpAPI/common.ts
  server/src/user/dto/rated-video-request.dto.ts
  server/src/user/dto/rated-video-response.dto.ts
  server/src/user/dto/rater-response.dto.ts
  server/src/user/user.controller.ts
  server/src/user/user.module.ts
  server/src/user/user.service.ts
  server/src/video/dto/rated-video-info.dto.ts
  server/src/video/video.controller.ts
  server/src/video/video.service.ts
Labels: backend, feat

#114 카테고리 별 top10 비디오 조회
  server/src/action/action.service.ts
  server/src/user/user.service.ts
  server/src/video/dto/random-video-response.dto.ts
  server/src/video/dto/top-video-query.dto.ts
  server/src/video/dto/video-rating.dto.ts
  server/src/video/video.controller.ts
  server/src/video/video.service.ts
Labels: backend, feat

#115 Manifest 파일 응답
  server/src/action/action.service.ts
  server/src/action/dto/manifest-query.dto.ts
  server/src/action/schemas/action.schema.ts
  server/src/decorators/ignore-interceptor.ts
  server/src/transform.interceptor.ts
  server/src/video/video.controller.ts
  server/src/video/video.service.ts
  server/transform.interceptor.ts
Labels: backend, feat

#116 trend top10 비디오 조회
  server/src/video/video.controller.ts
  server/src/video/video.service.ts
Labels: backend, feat

#124 LoginActivity 명칭 및 UI 수정
  client/presentation/src/main/AndroidManifest.xml
  client/presentation/src/main/java/com/everyone/movemove_android/ui/login/LoginScreen.kt
  client/presentation/src/main/java/com/everyone/movemove_android/ui/starting/StartingActivity.kt
  client/presentation/src/main/java/com/everyone/movemove_android/ui/starting/StartingContract.kt
  client/presentation/src/main/java/com/everyone/movemove_android/ui/starting/StartingScreen.kt
  client/presentation/src/main/java/com/everyone/movemove_android/ui/starting/StartingViewModel.kt
  client/presentation/src/main/java/com/everyone/movemove_android/ui/theme/Color.kt
  client/presentation/src/main/res/drawable/ic_google.xml
  client/presentation/src/main/res/drawable/ic_kakao.xml
  client/presentation/src/main/res/drawable/img_google_login.png
  client/presentation/src/main/res/raw/starting_video.mp4
  client/presentation/src/main/res/values/strings.xml
Labels: android, feat, chore

#126 네트워크 요청 및 응답 관련 수정
  client/data/src/main/java/com/everyone/data/base/ApiResponse.kt
  client/data/src/main/java/com/everyone/data/remote/NetworkHandler.kt
  client/data/src/main/java/com/everyone/data/remote/model/ApiResponse.kt
  client/data/src/main/java/com/everyone/data/remote/model/UrlParams.kt
  client/data/src/main/java/com/everyone/data/remote/model/UrlParamsBuilder.kt
  client/data/src/main/java/com/everyone/data/repository/MainRepositoryImpl.kt
  client/domain/src/main/java/com/everyone/domain/model/base/DataState.kt
  client/domain/src/main/java/com/everyone/domain/model/base/NetworkError.kt
  client/domain/src/main/java/com/everyone/domain/repository/MainRepository.kt
  client/domain/src/main/java/com/everyone/domain/usecase/GetVideoRandomUseCase.kt
Labels: android, chore, refactor

#129 별점 준 비디오 페이지네이션 버그 수정
  server/src/action/action.service.ts
  server/src/app.controller.ts
  server/src/exceptions/enum/exception.enum.ts
  server/src/exceptions/reason-required.exception.ts
  server/src/user/user.module.ts
  server/src/user/user.service.ts
  server/src/video/dto/ads-response.dto.ts
  server/src/video/dto/video-list-response.dto.ts
  server/src/video/video.controller.ts
  server/src/video/video.service.ts
Labels: backend, fix

#133 Starting 배경화면 영상 사이즈 버전 대응
  client/presentation/src/main/java/com/everyone/movemove_android/ui/starting/StartingScreen.kt
Labels: android, fix

#136 Backend CD
  .github/workflows/BE_CD.yml
  .github/workflows/BE_CICD.yml
  server/.dockerignore
  server/.gitignore
  server/Dockerfile
Labels: backend, chore

#137 BE CD 배포 설정
  .github/workflows/BE_CD.yml
Labels: backend, chore

#141 BE CD Docker 빌드 캐시 사용 테스트
  .github/workflows/BE_CD.yml
  server/src/main.ts
Labels: backend, chore

#142 BE CD 수정
  .github/workflows/BE_CD.yml
  server/src/main.ts
Labels: backend, chore

#147 presigned url 적용
  server/package.json
  server/src/app.controller.ts
  server/src/app.module.ts
  server/src/auth/auth.controller.ts
  server/src/auth/auth.service.ts
  server/src/ncpAPI/presignedURL.ts
  server/src/presigned-url/dto/advertisement-presigned-url-request.dto.ts
  server/src/presigned-url/dto/advertisement-presigned-url-response.dto.ts
  server/src/presigned-url/dto/presigned-url-response.dto.ts
  server/src/presigned-url/dto/profile-presigned-url-request.dto.ts
  server/src/presigned-url/dto/reissue-presigned-url-request.dto.ts
  server/src/presigned-url/dto/video-presigned-url-request.dto.ts
  server/src/presigned-url/dto/video-presigned-url-response.dto.ts
  server/src/presigned-url/presigned-url.controller.ts
  server/src/presigned-url/presigned-url.module.ts
  server/src/presigned-url/presigned-url.service.ts
  server/src/user/dto/profile-response.dto.ts
  server/src/user/dto/profile.dto.ts
  server/src/user/dto/uploader-response.dto.ts
  server/src/user/dto/user-info.dto.ts
  server/src/user/dto/user.dto.ts
  server/src/user/user.controller.ts
  server/src/user/user.service.ts
  server/src/video/dto/video-response.dto.ts
  server/src/video/dto/video.dto.ts
  server/src/video/video.controller.ts
  server/src/video/video.service.ts
  server/yarn.lock
Labels: backend, feat, refactor

#144 NCP 리스트 API 버전업
  server/package.json
  server/src/app.service.ts
  server/src/ncpAPI/common.ts
  server/src/ncpAPI/listObjects.ts
  server/yarn.lock
Labels: backend, feat

#153 비디오 조회수 증가
  server/src/action/action.controller.ts
  server/src/action/action.service.ts
  server/src/action/dto/manifest-query.dto.ts
  server/src/action/dto/view-response.dto.ts
  server/src/ncpAPI/presignedURL.ts
  server/src/user/user.controller.ts
  server/src/user/user.service.ts
  server/src/video/video.controller.ts
  server/src/video/video.service.ts
Labels: backend, feat

#140 회원가입 API 연결
  client/data/src/main/java/com/everyone/data/remote/model/JsonWebTokenResponse.kt
  client/data/src/main/java/com/everyone/data/remote/model/ProfileResponse.kt
  client/data/src/main/java/com/everyone/data/remote/model/UserInfoResponse.kt
  client/data/src/main/java/com/everyone/data/repository/UserRepositoryImpl.kt
  client/domain/src/main/java/com/everyone/domain/model/JsonWebToken.kt
  client/domain/src/main/java/com/everyone/domain/model/Profile.kt
  client/domain/src/main/java/com/everyone/domain/model/UserInfo.kt
  client/domain/src/main/java/com/everyone/domain/repository/UserRepository.kt
  client/domain/src/main/java/com/everyone/domain/usecase/SignUpUseCase.kt
  client/presentation/src/main/java/com/everyone/movemove_android/di/RepositoryModule.kt
  client/presentation/src/main/java/com/everyone/movemove_android/ui/screens/signup/SignUpActivity.kt
Labels: android, feat

#158 Presigned URL 관련 예외처리
  server/src/auth/auth.controller.ts
  server/src/auth/auth.service.ts
  server/src/exceptions/enum/exception.enum.ts
  server/src/exceptions/object-not-found.exception.ts
  server/src/exceptions/profile-upload-required-exception.ts
  server/src/exceptions/thumbnail-upload-required-exception copy 2.ts
  server/src/exceptions/video-upload-required-exception copy.ts
  server/src/ncpAPI/listObjects.ts
  server/src/ncpAPI/presignedURL.ts
  server/src/user/dto/profile.dto.ts
  server/src/user/dto/user-info.dto.ts
  server/src/user/dto/user.dto.ts
  server/src/user/user.controller.ts
  server/src/user/user.service.ts
Labels: backend, feat
